### ISSUE TITLE
The curly braces not visible when highlighted 

### ISSUE THREAD

**Issue by mayureshs** [tmacharia/pine-gap#1]
Love the theme so far. The curly braces when highlighted are not visible. Snapshot below

![image](https://user-images.githubusercontent.com/1014702/90255945-9b042200-de0a-11ea-8b32-c9f6762eaf61.png)

**Comment by tmacharia** [comment]
Looking into it right away.

**Comment by mayureshs** [comment]
Any update on this ?

**Comment by tmacharia** [comment]
> Any update on this ?

Still looking into it. Am hoping to get this resolved by end week.

**Comment by tmacharia** [comment]
@mayureshs Are you still experiencing this issue coz on my end it looks fine as shown below?

![image](https://user-images.githubusercontent.com/29064426/93118367-e3905300-f6c8-11ea-838f-89a305d98ab0.png)

**Comment by mayureshs** [comment]
When Resharper is enabled the issue occurs.

**Comment by tmacharia** [comment]
Oh, the extension doesn't have provision to handle overrides of other extensions at the moment. Someone asked about this as well regarding Resharper, you can [view the QnA here](https://marketplace.visualstudio.com/items?itemName=NeonClouds.pinegap-dark&ssr=false#qna) on Visual Studio Marketplace

**Comment by tmacharia** [comment]
Closing this for now.
