### ISSUE TITLE
In Solution Explorer the foreground of selected row, should be dark

### ISSUE THREAD

**Issue by pasqualedante** [tmacharia/pine-gap#2]
As shown in the attached screenshot, the white foreground in selected row is less readable.
Thanks in advance.
<img width="1052" alt="Immagine" src="https://user-images.githubusercontent.com/813690/91400043-4ff10280-e83f-11ea-988c-f9efc1b54d98.png">

**Comment by tmacharia** [comment]
I have resolved this and published an update **v1.2.1**

**Comment by pasqualedante** [comment]
It works fine, thanks.
